services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${USER_PASSWORD}

  web:
    build: .
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --no-input &&
               gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"

    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - logs_volume:/app/logs


    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5673:5672"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
      - media_volume:/app/media
      - logs_volume:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

    depends_on:
      - rabbitmq
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
  media_volume:
  logs_volume:

