# Generated by Django 6.0.4 on 2026-04-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gmail',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
