# Generated by Django 6.0.4 on 2026-04-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_customuser_address_order_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='gmail',
            new_name='email',
        ),
    ]
