# Generated by Django 6.0.4 on 2026-05-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_contactlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
